"""Alert model: a project risk warning generated by the central Agent.

Alerts are created when the Agent detects overdue tasks, inactive members,
blocked dependencies, or dependency chain risks.
"""

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.core.time import utc_now
from app.db.session import Base


class Alert(Base):
    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    project_id: Mapped[int] = mapped_column(ForeignKey("projects.id"), index=True)
    alert_type: Mapped[str] = mapped_column(
        String(32), default="overdue"
    )  # "overdue" | "no_update" | "blocked" | "dependency_chain"
    severity: Mapped[str] = mapped_column(
        String(16), default="warning"
    )  # "critical" | "warning" | "info"
    message: Mapped[str] = mapped_column(Text, default="")
    status: Mapped[str] = mapped_column(
        String(16), default="active"
    )  # "active" | "acknowledged" | "resolved"
    acknowledged_by: Mapped[str] = mapped_column(String(128), default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
